# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-02 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0013_auto_20180424_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'Closed')], default=0, help_text='The Status codes behavior should be defined into application.', verbose_name='Status code'),
        ),
    ]
